context:
  version: "1.2.1"
  xgb_version: "3.4.1"
  lightgbm_version: "4.6.0"

package:
  name: medpython
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/medpython/medpython-${{ version }}.tar.gz
  sha256: 316329bc0a3e5cb6abad145afc49751940a41b6095ec9c6f6543fe477992dc8c

build:
  number: 0
  script:
    - if: win
      then:
        - set "CMAKE_GENERATOR_TOOLSET=v143"
        - set "CXXFLAGS=%CXXFLAGS% /openmp:llvm /I%LIBRARY_INC%"
        - set "LDFLAGS=%LDFLAGS% /LIBPATH:%LIBRARY_LIB%"
    - python -m pip install . --no-deps -vv

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - make
    - swig
  host:
    - python
    - setuptools >=61.0
    - wheel
    - numpy
    - pip
    - eigen
    - libboost-headers
    # medpython uses XGBoost's C++ interfaces, which require a compatible C++ ABI.
    # On Windows, build XGBoost from source with MSVC alongside medpython.
    - if: not win
      then: libxgboost ==${{ xgb_version }}
    - dmlc
    - nlohmann_json
    - liblightgbm ==${{ lightgbm_version }}
    - if: linux
      then: libgomp
      else: llvm-openmp
  run:
    - python
    - pandas
    - plotly
    - numpy
    - medpython-etl
    - if: not win
      then: libxgboost ==${{ xgb_version }}

tests:
  - python:
      imports:
        - med
        - AlgoMarker
      pip_check: true

  - script:
      - python tests/run_all.py
    requirements:
      run:
        - requests
    files:
      recipe:
        - tests/

about:
  homepage: https://github.com/Medial-EarlySign/medpython
  documentation: https://medial-earlysign.github.io/MR_Wiki
  repository: https://github.com/Medial-EarlySign/medpython
  summary: Medial EarlySign Python Library for Electronical Medical Records
  description: |
    Medial EarlySign Infrastructure for machine learning on Electronical Medical Records
  license: MIT
  license_file:
    - LICENCE

extra:
  recipe-maintainers:
    - alonyado
